import ProjectWriteup from '../components/ProjectWriteup'

const sections = [
  { id: 'overview', label: 'Overview' },
  { id: 'problem', label: 'The Problem' },
  { id: 'architecture', label: 'Architecture' },
  { id: 'agents', label: 'Agent Roles' },
  { id: 'pipeline', label: 'Pipeline Flow' },
  { id: 'stack', label: 'Tech Stack' },
  { id: 'outcome', label: 'Outcome' },
]

function Content() {
  return (
    <div className="space-y-16 md:space-y-20">
      {/* Overview */}
      <section id="overview" data-section>
        <h2 className="font-heading font-bold text-2xl md:text-3xl text-offwhite mb-6">
          Overview
        </h2>
        <p className="font-heading text-offwhite/60 text-base md:text-lg leading-relaxed mb-4">
          The Autonomous App Factory is a multi-agent AI pipeline that transforms a single client brief into production-ready software. No templates, no boilerplate — every output is custom-generated by specialised AI agents working in concert.
        </p>
        <p className="font-heading text-offwhite/60 text-base md:text-lg leading-relaxed">
          The system handles everything from market research to deployment, producing code, assets, metadata, and marketing copy from one input. It demonstrates that an AI-native workflow can compress what traditionally takes a team of six into a single automated pipeline.
        </p>
      </section>

      {/* The Problem */}
      <section id="problem" data-section>
        <h2 className="font-heading font-bold text-2xl md:text-3xl text-offwhite mb-6">
          The Problem
        </h2>
        <p className="font-heading text-offwhite/60 text-base md:text-lg leading-relaxed mb-4">
          Building a production app involves dozens of discrete tasks: researching the market, scoping features, architecting systems, writing code, designing assets, reviewing quality, and deploying infrastructure. Each step typically requires a different specialist and handoff friction slows everything down.
        </p>
        <p className="font-heading text-offwhite/60 text-base md:text-lg leading-relaxed">
          The question I wanted to answer: what if AI agents could own each of those responsibilities autonomously, coordinated by an orchestrator that understands the full context?
        </p>
      </section>

      {/* Architecture */}
      <section id="architecture" data-section>
        <h2 className="font-heading font-bold text-2xl md:text-3xl text-offwhite mb-6">
          Architecture
        </h2>
        <div className="bg-[#1A1210] border border-offwhite/[0.06] rounded-2xl p-6 md:p-8 mb-6">
          <div className="font-mono text-[11px] text-offwhite/50 leading-relaxed space-y-1">
            <p className="text-offwhite/30">{'// Pipeline architecture'}</p>
            <p><span className="text-signal">Client Brief</span></p>
            <p>&nbsp;&nbsp;{'→'} <span className="text-offwhite/70">Jarvis</span> (orchestration + routing)</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;{'→'} <span className="text-offwhite/70">Sola</span> (research + competitive analysis)</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;{'→'} <span className="text-offwhite/70">Archie</span> (architecture + system design)</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;{'→'} <span className="text-offwhite/70">Kai</span> (code generation + build)</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;{'→'} <span className="text-offwhite/70">Iris</span> (code review + QA)</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;{'→'} <span className="text-offwhite/70">Luna</span> (asset generation)</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;{'→'} <span className="text-offwhite/70">Dash</span> (deployment)</p>
            <p>&nbsp;&nbsp;{'→'} <span className="text-signal">Production App</span></p>
          </div>
        </div>
        <p className="font-heading text-offwhite/60 text-base md:text-lg leading-relaxed">
          The pipeline is sequential where dependencies exist, but parallelised where possible. Jarvis maintains a shared state object that flows through each agent, accumulating context and outputs. Every agent reads from and writes to this state, so downstream agents always have full context.
        </p>
      </section>

      {/* Agent Roles */}
      <section id="agents" data-section>
        <h2 className="font-heading font-bold text-2xl md:text-3xl text-offwhite mb-6">
          Agent Roles
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {[
            { name: 'Jarvis', role: 'Orchestrator', desc: 'Routes tasks, maintains state, coordinates the full pipeline lifecycle.' },
            { name: 'Sola', role: 'Researcher', desc: 'Competitive analysis, market research, feature recommendations based on real data.' },
            { name: 'Archie', role: 'Architect', desc: 'System design, service boundaries, database schema, API contracts.' },
            { name: 'Kai', role: 'Builder', desc: 'Code generation across frontend, backend, and infrastructure.' },
            { name: 'Iris', role: 'Reviewer', desc: 'Automated code review, security checks, best-practice enforcement.' },
            { name: 'Luna', role: 'Designer', desc: 'Icon generation, screenshot creation, visual asset production.' },
            { name: 'Echo', role: 'Writer', desc: 'Marketing copy, App Store metadata, documentation.' },
            { name: 'Dash', role: 'Deployer', desc: 'CI/CD pipeline, domain setup, production deployment.' },
          ].map((agent) => (
            <div
              key={agent.name}
              className="bg-offwhite/[0.03] border border-offwhite/[0.06] rounded-xl p-4 md:p-5"
            >
              <div className="flex items-center gap-2 mb-2">
                <span className="font-heading font-bold text-sm text-offwhite">{agent.name}</span>
                <span className="font-mono text-[10px] text-signal">{agent.role}</span>
              </div>
              <p className="font-heading text-sm text-offwhite/40 leading-relaxed">{agent.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pipeline Flow */}
      <section id="pipeline" data-section>
        <h2 className="font-heading font-bold text-2xl md:text-3xl text-offwhite mb-6">
          Pipeline Flow
        </h2>
        <div className="space-y-4">
          {[
            { step: '01', title: 'Brief Ingestion', desc: 'The client brief is parsed and structured into a project state object with goals, constraints, and success criteria.' },
            { step: '02', title: 'Research Phase', desc: 'Sola analyses the market, identifies competitors, and recommends features and positioning based on real data.' },
            { step: '03', title: 'Architecture', desc: 'Archie designs the system — services, data models, API contracts, and infrastructure requirements.' },
            { step: '04', title: 'Code Generation', desc: 'Kai generates production code across the full stack, following the architecture spec and coding standards.' },
            { step: '05', title: 'Quality Assurance', desc: 'Iris reviews every file for bugs, security issues, and best-practice violations. Failed reviews loop back to Kai.' },
            { step: '06', title: 'Asset Creation', desc: 'Luna generates icons, screenshots, and brand assets. Echo writes marketing copy and metadata.' },
            { step: '07', title: 'Deployment', desc: 'Dash handles CI/CD setup, domain configuration, and production deployment. The app goes live.' },
          ].map((item) => (
            <div key={item.step} className="flex gap-4 md:gap-6">
              <div className="shrink-0 w-10 h-10 rounded-lg bg-signal/10 border border-signal/20 flex items-center justify-center">
                <span className="font-mono text-xs text-signal">{item.step}</span>
              </div>
              <div className="pt-1">
                <h4 className="font-heading font-semibold text-base text-offwhite mb-1">{item.title}</h4>
                <p className="font-heading text-sm text-offwhite/40 leading-relaxed">{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Tech Stack */}
      <section id="stack" data-section>
        <h2 className="font-heading font-bold text-2xl md:text-3xl text-offwhite mb-6">
          Tech Stack
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {[
            { category: 'Core', items: 'Python, Multi-Agent Framework' },
            { category: 'AI Models', items: 'GPT-4o, Claude, DALL-E 3, Google Imagen' },
            { category: 'Orchestration', items: 'Custom state machine, prompt chaining' },
            { category: 'Output', items: 'Swift/React code, Supabase schemas, Netlify deploys' },
          ].map((row) => (
            <div key={row.category} className="bg-offwhite/[0.03] border border-offwhite/[0.06] rounded-xl p-4">
              <span className="font-mono text-[10px] text-signal uppercase block mb-1">{row.category}</span>
              <span className="font-heading text-sm text-offwhite/60">{row.items}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Outcome */}
      <section id="outcome" data-section>
        <h2 className="font-heading font-bold text-2xl md:text-3xl text-offwhite mb-6">
          Outcome
        </h2>
        <p className="font-heading text-offwhite/60 text-base md:text-lg leading-relaxed mb-4">
          The Autonomous App Factory proves that a well-orchestrated AI pipeline can handle the full breadth of software development. From a single brief, it produces production-grade code, visual assets, marketing copy, and deployed infrastructure.
        </p>
        <p className="font-heading text-offwhite/60 text-base md:text-lg leading-relaxed mb-8">
          This isn't a toy demo — it's production-level architecture designed to scale. Every agent is modular, every output is structured, and the entire pipeline is reproducible.
        </p>
        <div className="flex flex-wrap gap-6">
          {[
            { metric: '9', label: 'AI Agents' },
            { metric: '7', label: 'Pipeline stages' },
            { metric: '1', label: 'Input required' },
          ].map((stat) => (
            <div key={stat.label}>
              <span className="font-heading font-bold text-3xl md:text-4xl text-signal block">{stat.metric}</span>
              <span className="font-mono text-[10px] text-offwhite/30 uppercase">{stat.label}</span>
            </div>
          ))}
        </div>
      </section>
    </div>
  )
}

export default function FactoryWriteup() {
  return (
    <ProjectWriteup
      project={{
        title: 'Autonomous App Factory',
        tagline: 'From client brief to production app — fully automated.',
        year: '2025',
        tags: ['Python', 'Multi-Agent', 'LLM Orchestration', 'Prompt Chaining'],
        github: 'https://github.com/u-kaushik/Auto-App-Factory-Portfolio',
        live: 'https://demoautoappfactory.netlify.app/',
        sections,
        content: <Content />,
      }}
    />
  )
}
